# Generated by Django 6.0.2 on 2026-02-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="pseudonym",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
